services:
  client-react-nginx:
    image: ashishkhanagwal/docker-web-app-client-react-nginx:5
    # labels:
    #   shipyard.primary-route: true
    #   shipyard.route: "/"
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
  api-node:
    image: ashishkhanagwal/docker-web-app-api-node:9
    # labels:
    #   shipyard.route: "/api/node/"
    #   shipyard.route.rewrite: true
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
  api-golang:
    image: ashishkhanagwal/docker-web-app-api-golang:8
    # labels:
    #   shipyard.route: "/api/golang/"
    #   shipyard.route.rewrite: true
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend:
